# Generated by Django 3.0.5 on 2020-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run_ID', models.CharField(max_length=120)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Run_status', models.TextField()),
                ('count', models.IntegerField()),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
