# Generated by Django 3.0.5 on 2020-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, unique=True)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published', models.DateField()),
                ('cover', models.ImageField(upload_to='cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run_ID', models.CharField(max_length=120)),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Run_status', models.TextField()),
                ('count', models.IntegerField()),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
